name: 📋 Task
description: 스프린트/마일스톤 단위의 상위 작업
title: "[TASK] "
labels: ["task"]
type: "Task"
body:
  # Header
  - type: markdown
    attributes:
      value: |
        ## 📌 Task 이슈 가이드
        - 특정 **마일스톤/스프린트**의 상위 작업 정의를 위한 이슈
        - 하위 이슈 Subtasks로 연결, **양방향 연결** 유지
        - DoR/DoD 체크리스트를 통해 시작/완료 기준을 명시

  # 0) 상위 연결(선택)
  - type: input
    id: parent_task
    attributes:
      label: ↗️ 상위 Task (선택)
      placeholder: "#42"

  # Body

  # 1) 배경/목표
  - type: textarea
    id: objective
    attributes:
      label: 🎯 목표 및 개요
      description: Task 목적, 기대효과
      placeholder: |
        예) 회원가입 전반(화면/검증/API/이메일 인증)을 2025-09 스프린트 내 안정화
    validations:
      required: true

  # 2) 범위
  - type: textarea
    id: in_scope
    attributes:
      label: ✅ 범위(In Scope)
      description: 이 Task에 포함되는 기능/변경사항
      placeholder: |
        - FE: /signup 페이지 UI, Validation, 상태관리
        - BE: Signup API, 이메일 인증, Rate Limit
  - type: textarea
    id: out_of_scope
    attributes:
      label: ❌ 범위 제외(Out of Scope)
      description: 이번 Task에서 다루지 않을 것들(스코프 크리프 방지)
      placeholder: |
        - 소셜 로그인 연동(Google/Apple): 다음 스프린트로 이관

  # 3) 산출물/연결 자료
  - type: textarea
    id: artifacts
    attributes:
      label: 📦 산출물/아티팩트
      description: |
        산출물 유형 및 링크(예: 문서, 다이어그램, 배포 링크, Storybook, API 문서 등)
      placeholder: |
        - ADR: ...
        - API 문서: ...
        - Storybook: ...
        - 배포 링크: ...

  # 4) 스프린트/마일스톤
  - type: input
    id: milestone
    attributes:
      label: 🗓️ 마일스톤/스프린트 이름
      placeholder: 2025-09 Sprint 1

  # 5) 우선순위/규모
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 우선순위
      options: [P0-urgent, P1-high, P2-med, P3-low]
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: 📏 규모(Size, 상대평가)
      description: 상대적 난이도/노력치
      options: [S, M, L]
    validations:
      required: true

  # 6) 의존/리스크
  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 의존성/블로킹 이슈
      description: 선행되어야 하거나 현재 막고 있는 이슈/PR/외부 요인
      placeholder: |
        - 선행: #123 PR 병합 필요
        - 외부: 이메일 발송 계정 승인 대기

  - type: checkboxes
    id: risks
    attributes:
      label: ⚠️ 리스크/주의사항
      options:
        - label: 보안/권한/비용 영향 가능
        - label: 성능/확장성 영향 가능
        - label: 데이터 마이그레이션 필요
        - label: 협업팀(디자인/인프라) 일정 영향

  # Footer
  # 7) 수용 기준(AC) & 완료 정의(DoD)
  - type: textarea
    id: ac
    attributes:
      label: ✅ 수용 기준(AC)
      description: 기능/행동 단위로 테스트 가능한 문장으로 작성
      placeholder: |
        - [ ] 비로그인 사용자가 /signup 접근 시 폼이 노출된다
        - [ ] 이메일 인증 토큰이 만료되면 재발급 안내가 노출된다
        - [ ] p95 응답시간 < 300ms (Signup API)

  - type: checkboxes
    id: dod
    attributes:
      label: 🧾 완료 정의(DoD)
      description: 완료 시 반드시 충족되어야 할 항목
      options:
        - label: 테스트 통과 및 커버리지 기준 충족
        - label: 관련 이슈/PR 연결(Closes/Fixes) 및 라벨 정리
        - label: 문서/ADR/CHANGELOG 업데이트
        - label: 관측(로그/모니터링/알람) 확인
        - label: Notion 요약/프로젝트 상태 갱신

  # 8) 하위 이슈 분할 & 양방향 연결
  - type: textarea
    id: subtasks
    attributes:
      label: 🧩 Subtasks (체크리스트 → 이슈 연결)
      description: 하위 작업 분할, 항목 별 이슈 생성
      placeholder: |
        - [ ] FE
          - [ ] FEAT: 회원가입 페이지 구현 # (필요 시 #123 형태로 연결)
        - [ ] BE
          - [ ] FEAT: 회원가입 API 구현 #
          - [ ] Docs: API 문서 및 Notion 정리 #
        - [ ] Docs
            - [ ] Docs: Notion 요약 및 프로젝트 상태 갱신 #

  # 9) 참고 자료
  - type: textarea
    id: references
    attributes:
    label: 📚 참고 자료
    placeholder: |
      - RFC 7231 Hypertext Transfer Protocol
      - Spring Boot Docs: ...
